(ns javax.tools.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.tools.Diagnostic$Kind])
(require '[javax.tools.Diagnostic])
(require '[javax.tools.DiagnosticCollector])
(require '[javax.tools.DiagnosticListener])
(require '[javax.tools.DocumentationTool$DocumentationTask])
(require '[javax.tools.DocumentationTool$Location])
(require '[javax.tools.DocumentationTool])
(require '[javax.tools.FileObject])
(require '[javax.tools.ForwardingFileObject])
(require '[javax.tools.ForwardingJavaFileManager])
(require '[javax.tools.ForwardingJavaFileObject])
(require '[javax.tools.JavaCompiler$CompilationTask])
(require '[javax.tools.JavaCompiler])
(require '[javax.tools.JavaFileManager$Location])
(require '[javax.tools.JavaFileManager])
(require '[javax.tools.JavaFileObject$Kind])
(require '[javax.tools.JavaFileObject])
(require '[javax.tools.OptionChecker])
(require '[javax.tools.SimpleJavaFileObject])
(require '[javax.tools.StandardJavaFileManager])
(require '[javax.tools.StandardLocation])
(require '[javax.tools.Tool])
(require '[javax.tools.ToolProvider])
