(ns javax.crypto.spec.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.crypto.spec.DESKeySpec])
(require '[javax.crypto.spec.DESedeKeySpec])
(require '[javax.crypto.spec.DHGenParameterSpec])
(require '[javax.crypto.spec.DHParameterSpec])
(require '[javax.crypto.spec.DHPrivateKeySpec])
(require '[javax.crypto.spec.DHPublicKeySpec])
(require '[javax.crypto.spec.GCMParameterSpec])
(require '[javax.crypto.spec.IvParameterSpec])
(require '[javax.crypto.spec.OAEPParameterSpec])
(require '[javax.crypto.spec.PBEKeySpec])
(require '[javax.crypto.spec.PBEParameterSpec])
(require '[javax.crypto.spec.PSource$PSpecified])
(require '[javax.crypto.spec.PSource])
(require '[javax.crypto.spec.RC2ParameterSpec])
(require '[javax.crypto.spec.RC5ParameterSpec])
(require '[javax.crypto.spec.SecretKeySpec])
