(ns javax.swing.plaf.multi.MultiFileChooserUI
  "A multiplexing UI used to combine FileChooserUIs.

  This file was automatically generated by AutoMulti."
  (:refer-clojure :only [require comment defn ->])
  (:import [javax.swing.plaf.multi MultiFileChooserUI]))

(defn ->multi-file-chooser-ui
  "Constructor."
  ([]
    (new MultiFileChooserUI )))

(defn *create-ui
  "Returns a multiplexing UI instance if any of the auxiliary
   LookAndFeels supports this UI.  Otherwise, just returns the
   UI object obtained from the default LookAndFeel.

  a - `javax.swing.JComponent`

  returns: `javax.swing.plaf.ComponentUI`"
  ([a]
    (MultiFileChooserUI/createUI a)))

(defn install-ui
  "Invokes the installUI method on each UI handled by this object.

  a - the component where this UI delegate is being installed - `javax.swing.JComponent`"
  ([this a]
    (-> this (.installUI a))))

(defn get-minimum-size
  "Invokes the getMinimumSize method on each UI handled by this object.

  a - the component whose minimum size is being queried; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `java.awt.Dimension`"
  ([this a]
    (-> this (.getMinimumSize a))))

(defn get-maximum-size
  "Invokes the getMaximumSize method on each UI handled by this object.

  a - the component whose maximum size is being queried; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `java.awt.Dimension`"
  ([this a]
    (-> this (.getMaximumSize a))))

(defn get-accessible-child
  "Invokes the getAccessibleChild method on each UI handled by this object.

  a - `javax.swing.JComponent`
  b - `int`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `javax.accessibility.Accessible`"
  ([this a b]
    (-> this (.getAccessibleChild a b))))

(defn get-u-is
  "Returns the list of UIs associated with this multiplexing UI.  This
   allows processing of the UIs by an application aware of multiplexing
   UIs on components.

  returns: `javax.swing.plaf.ComponentUI[]`"
  ([this]
    (-> this (.getUIs))))

(defn get-approve-button-text
  "Invokes the getApproveButtonText method on each UI handled by this object.

  a - `javax.swing.JFileChooser`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `java.lang.String`"
  ([this a]
    (-> this (.getApproveButtonText a))))

(defn uninstall-ui
  "Invokes the uninstallUI method on each UI handled by this object.

  a - the component from which this UI delegate is being removed; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`"
  ([this a]
    (-> this (.uninstallUI a))))

(defn contains
  "Invokes the contains method on each UI handled by this object.

  a - the component where the x,y location is being queried; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`
  b - the x coordinate of the point - `int`
  c - the y coordinate of the point - `int`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `boolean`"
  ([this a b c]
    (-> this (.contains a b c))))

(defn get-accept-all-file-filter
  "Invokes the getAcceptAllFileFilter method on each UI handled by this object.

  a - `javax.swing.JFileChooser`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `javax.swing.filechooser.FileFilter`"
  ([this a]
    (-> this (.getAcceptAllFileFilter a))))

(defn update
  "Invokes the update method on each UI handled by this object.

  a - the Graphics context in which to paint - `java.awt.Graphics`
  b - the component being painted; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`"
  ([this a b]
    (-> this (.update a b))))

(defn get-dialog-title
  "Invokes the getDialogTitle method on each UI handled by this object.

  a - `javax.swing.JFileChooser`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `java.lang.String`"
  ([this a]
    (-> this (.getDialogTitle a))))

(defn ensure-file-is-visible
  "Invokes the ensureFileIsVisible method on each UI handled by this object.

  a - `javax.swing.JFileChooser`
  b - `java.io.File`"
  ([this a b]
    (-> this (.ensureFileIsVisible a b))))

(defn get-accessible-children-count
  "Invokes the getAccessibleChildrenCount method on each UI handled by this object.

  a - `javax.swing.JComponent`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `int`"
  ([this a]
    (-> this (.getAccessibleChildrenCount a))))

(defn rescan-current-directory
  "Invokes the rescanCurrentDirectory method on each UI handled by this object.

  a - `javax.swing.JFileChooser`"
  ([this a]
    (-> this (.rescanCurrentDirectory a))))

(defn paint
  "Invokes the paint method on each UI handled by this object.

  a - the Graphics context in which to paint - `java.awt.Graphics`
  b - the component being painted; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`"
  ([this a b]
    (-> this (.paint a b))))

(defn get-file-view
  "Invokes the getFileView method on each UI handled by this object.

  a - `javax.swing.JFileChooser`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `javax.swing.filechooser.FileView`"
  ([this a]
    (-> this (.getFileView a))))

(defn get-preferred-size
  "Invokes the getPreferredSize method on each UI handled by this object.

  a - the component whose preferred size is being queried; this argument is often ignored, but might be used if the UI object is stateless and shared by multiple components - `javax.swing.JComponent`

  returns: the value obtained from the first UI, which is
   the UI obtained from the default LookAndFeel - `java.awt.Dimension`"
  ([this a]
    (-> this (.getPreferredSize a))))

