(ns javax.activation.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.activation.ActivationDataFlavor])
(require '[javax.activation.CommandInfo])
(require '[javax.activation.CommandMap])
(require '[javax.activation.CommandObject])
(require '[javax.activation.DataContentHandler])
(require '[javax.activation.DataContentHandlerFactory])
(require '[javax.activation.DataHandler])
(require '[javax.activation.DataSource])
(require '[javax.activation.FileDataSource])
(require '[javax.activation.FileTypeMap])
(require '[javax.activation.MailcapCommandMap])
(require '[javax.activation.MimeType])
(require '[javax.activation.MimeTypeParameterList])
(require '[javax.activation.MimeTypeParseException])
(require '[javax.activation.MimetypesFileTypeMap])
(require '[javax.activation.URLDataSource])
(require '[javax.activation.UnsupportedDataTypeException])
