(ns jdk.rmi.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[jdk.rmi.AccessException])
(require '[jdk.rmi.AlreadyBoundException])
(require '[jdk.rmi.ConnectException])
(require '[jdk.rmi.ConnectIOException])
(require '[jdk.rmi.MarshalException])
(require '[jdk.rmi.MarshalledObject])
(require '[jdk.rmi.Naming])
(require '[jdk.rmi.NoSuchObjectException])
(require '[jdk.rmi.NotBoundException])
(require '[jdk.rmi.RMISecurityException])
(require '[jdk.rmi.RMISecurityManager])
(require '[jdk.rmi.Remote])
(require '[jdk.rmi.RemoteException])
(require '[jdk.rmi.ServerError])
(require '[jdk.rmi.ServerException])
(require '[jdk.rmi.ServerRuntimeException])
(require '[jdk.rmi.StubNotFoundException])
(require '[jdk.rmi.UnexpectedException])
(require '[jdk.rmi.UnknownHostException])
(require '[jdk.rmi.UnmarshalException])
