(ns core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.swing.core])
(require '[javax.swing.border.core])
(require '[javax.swing.colorchooser.core])
(require '[javax.swing.event.core])
(require '[javax.swing.filechooser.core])
(require '[javax.swing.plaf.core])
(require '[javax.swing.plaf.basic.core])
(require '[javax.swing.plaf.metal.core])
(require '[javax.swing.plaf.multi.core])
(require '[javax.swing.plaf.nimbus.core])
(require '[javax.swing.plaf.synth.core])
(require '[javax.swing.table.core])
(require '[javax.swing.text.core])
(require '[javax.swing.text.html.core])
(require '[javax.swing.text.html.parser.core])
(require '[javax.swing.text.rtf.core])
(require '[javax.swing.tree.core])
(require '[javax.swing.undo.core])
