(ns javax.xml.crypto.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.xml.crypto.AlgorithmMethod])
(require '[javax.xml.crypto.Data])
(require '[javax.xml.crypto.KeySelector$Purpose])
(require '[javax.xml.crypto.KeySelector])
(require '[javax.xml.crypto.KeySelectorException])
(require '[javax.xml.crypto.KeySelectorResult])
(require '[javax.xml.crypto.MarshalException])
(require '[javax.xml.crypto.NoSuchMechanismException])
(require '[javax.xml.crypto.NodeSetData])
(require '[javax.xml.crypto.OctetStreamData])
(require '[javax.xml.crypto.URIDereferencer])
(require '[javax.xml.crypto.URIReference])
(require '[javax.xml.crypto.URIReferenceException])
(require '[javax.xml.crypto.XMLCryptoContext])
(require '[javax.xml.crypto.XMLStructure])
