(ns jdk.rmi.activation.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[jdk.rmi.activation.Activatable])
(require '[jdk.rmi.activation.ActivateFailedException])
(require '[jdk.rmi.activation.ActivationDesc])
(require '[jdk.rmi.activation.ActivationException])
(require '[jdk.rmi.activation.ActivationGroup])
(require '[jdk.rmi.activation.ActivationGroupDesc$CommandEnvironment])
(require '[jdk.rmi.activation.ActivationGroupDesc])
(require '[jdk.rmi.activation.ActivationGroupID])
(require '[jdk.rmi.activation.ActivationGroup_Stub])
(require '[jdk.rmi.activation.ActivationID])
(require '[jdk.rmi.activation.ActivationInstantiator])
(require '[jdk.rmi.activation.ActivationMonitor])
(require '[jdk.rmi.activation.ActivationSystem])
(require '[jdk.rmi.activation.Activator])
(require '[jdk.rmi.activation.UnknownGroupException])
(require '[jdk.rmi.activation.UnknownObjectException])
