(ns jdk.awt.dnd.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[jdk.awt.dnd.Autoscroll])
(require '[jdk.awt.dnd.DnDConstants])
(require '[jdk.awt.dnd.DragGestureEvent])
(require '[jdk.awt.dnd.DragGestureListener])
(require '[jdk.awt.dnd.DragGestureRecognizer])
(require '[jdk.awt.dnd.DragSource])
(require '[jdk.awt.dnd.DragSourceAdapter])
(require '[jdk.awt.dnd.DragSourceContext])
(require '[jdk.awt.dnd.DragSourceDragEvent])
(require '[jdk.awt.dnd.DragSourceDropEvent])
(require '[jdk.awt.dnd.DragSourceEvent])
(require '[jdk.awt.dnd.DragSourceListener])
(require '[jdk.awt.dnd.DragSourceMotionListener])
(require '[jdk.awt.dnd.DropTarget$DropTargetAutoScroller])
(require '[jdk.awt.dnd.DropTarget])
(require '[jdk.awt.dnd.DropTargetAdapter])
(require '[jdk.awt.dnd.DropTargetContext])
(require '[jdk.awt.dnd.DropTargetDragEvent])
(require '[jdk.awt.dnd.DropTargetDropEvent])
(require '[jdk.awt.dnd.DropTargetEvent])
(require '[jdk.awt.dnd.DropTargetListener])
(require '[jdk.awt.dnd.InvalidDnDOperationException])
(require '[jdk.awt.dnd.MouseDragGestureRecognizer])
