(ns javax.imageio.stream.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.imageio.stream.FileCacheImageInputStream])
(require '[javax.imageio.stream.FileCacheImageOutputStream])
(require '[javax.imageio.stream.FileImageInputStream])
(require '[javax.imageio.stream.FileImageOutputStream])
(require '[javax.imageio.stream.IIOByteBuffer])
(require '[javax.imageio.stream.ImageInputStream])
(require '[javax.imageio.stream.ImageInputStreamImpl])
(require '[javax.imageio.stream.ImageOutputStream])
(require '[javax.imageio.stream.ImageOutputStreamImpl])
(require '[javax.imageio.stream.MemoryCacheImageInputStream])
(require '[javax.imageio.stream.MemoryCacheImageOutputStream])
