(ns jdk.util.zip.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[jdk.util.zip.Adler32])
(require '[jdk.util.zip.CRC32])
(require '[jdk.util.zip.CheckedInputStream])
(require '[jdk.util.zip.CheckedOutputStream])
(require '[jdk.util.zip.Checksum])
(require '[jdk.util.zip.DataFormatException])
(require '[jdk.util.zip.Deflater])
(require '[jdk.util.zip.DeflaterInputStream])
(require '[jdk.util.zip.DeflaterOutputStream])
(require '[jdk.util.zip.GZIPInputStream])
(require '[jdk.util.zip.GZIPOutputStream])
(require '[jdk.util.zip.Inflater])
(require '[jdk.util.zip.InflaterInputStream])
(require '[jdk.util.zip.InflaterOutputStream])
(require '[jdk.util.zip.ZipEntry])
(require '[jdk.util.zip.ZipError])
(require '[jdk.util.zip.ZipException])
(require '[jdk.util.zip.ZipFile])
(require '[jdk.util.zip.ZipInputStream])
(require '[jdk.util.zip.ZipOutputStream])
