(ns javax.naming.directory.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.naming.directory.Attribute])
(require '[javax.naming.directory.AttributeInUseException])
(require '[javax.naming.directory.AttributeModificationException])
(require '[javax.naming.directory.Attributes])
(require '[javax.naming.directory.BasicAttribute])
(require '[javax.naming.directory.BasicAttributes])
(require '[javax.naming.directory.DirContext])
(require '[javax.naming.directory.InitialDirContext])
(require '[javax.naming.directory.InvalidAttributeIdentifierException])
(require '[javax.naming.directory.InvalidAttributeValueException])
(require '[javax.naming.directory.InvalidAttributesException])
(require '[javax.naming.directory.InvalidSearchControlsException])
(require '[javax.naming.directory.InvalidSearchFilterException])
(require '[javax.naming.directory.ModificationItem])
(require '[javax.naming.directory.NoSuchAttributeException])
(require '[javax.naming.directory.SchemaViolationException])
(require '[javax.naming.directory.SearchControls])
(require '[javax.naming.directory.SearchResult])
