(ns jdk.awt.font.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[jdk.awt.font.FontRenderContext])
(require '[jdk.awt.font.GlyphJustificationInfo])
(require '[jdk.awt.font.GlyphMetrics])
(require '[jdk.awt.font.GlyphVector])
(require '[jdk.awt.font.GraphicAttribute])
(require '[jdk.awt.font.ImageGraphicAttribute])
(require '[jdk.awt.font.LayoutPath])
(require '[jdk.awt.font.LineBreakMeasurer])
(require '[jdk.awt.font.LineMetrics])
(require '[jdk.awt.font.MultipleMaster])
(require '[jdk.awt.font.NumericShaper$Range])
(require '[jdk.awt.font.NumericShaper])
(require '[jdk.awt.font.OpenType])
(require '[jdk.awt.font.ShapeGraphicAttribute])
(require '[jdk.awt.font.TextAttribute])
(require '[jdk.awt.font.TextHitInfo])
(require '[jdk.awt.font.TextLayout$CaretPolicy])
(require '[jdk.awt.font.TextLayout])
(require '[jdk.awt.font.TextMeasurer])
(require '[jdk.awt.font.TransformAttribute])
