(ns jdk.util.logging.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[jdk.util.logging.ConsoleHandler])
(require '[jdk.util.logging.ErrorManager])
(require '[jdk.util.logging.FileHandler])
(require '[jdk.util.logging.Filter])
(require '[jdk.util.logging.Formatter])
(require '[jdk.util.logging.Handler])
(require '[jdk.util.logging.Level])
(require '[jdk.util.logging.LogManager])
(require '[jdk.util.logging.LogRecord])
(require '[jdk.util.logging.Logger])
(require '[jdk.util.logging.LoggingMXBean])
(require '[jdk.util.logging.LoggingPermission])
(require '[jdk.util.logging.MemoryHandler])
(require '[jdk.util.logging.SimpleFormatter])
(require '[jdk.util.logging.SocketHandler])
(require '[jdk.util.logging.StreamHandler])
(require '[jdk.util.logging.XMLFormatter])
