(ns javax.xml.crypto.dsig.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.xml.crypto.dsig.CanonicalizationMethod])
(require '[javax.xml.crypto.dsig.DigestMethod])
(require '[javax.xml.crypto.dsig.Manifest])
(require '[javax.xml.crypto.dsig.Reference])
(require '[javax.xml.crypto.dsig.SignatureMethod])
(require '[javax.xml.crypto.dsig.SignatureProperties])
(require '[javax.xml.crypto.dsig.SignatureProperty])
(require '[javax.xml.crypto.dsig.SignedInfo])
(require '[javax.xml.crypto.dsig.Transform])
(require '[javax.xml.crypto.dsig.TransformException])
(require '[javax.xml.crypto.dsig.TransformService])
(require '[javax.xml.crypto.dsig.XMLObject])
(require '[javax.xml.crypto.dsig.XMLSignContext])
(require '[javax.xml.crypto.dsig.XMLSignature$SignatureValue])
(require '[javax.xml.crypto.dsig.XMLSignature])
(require '[javax.xml.crypto.dsig.XMLSignatureException])
(require '[javax.xml.crypto.dsig.XMLSignatureFactory])
(require '[javax.xml.crypto.dsig.XMLValidateContext])
