(ns javax.xml.transform.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.xml.transform.ErrorListener])
(require '[javax.xml.transform.OutputKeys])
(require '[javax.xml.transform.Result])
(require '[javax.xml.transform.Source])
(require '[javax.xml.transform.SourceLocator])
(require '[javax.xml.transform.Templates])
(require '[javax.xml.transform.Transformer])
(require '[javax.xml.transform.TransformerConfigurationException])
(require '[javax.xml.transform.TransformerException])
(require '[javax.xml.transform.TransformerFactory])
(require '[javax.xml.transform.TransformerFactoryConfigurationError])
(require '[javax.xml.transform.URIResolver])
