(ns javax.imageio.spi.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.imageio.spi.IIORegistry])
(require '[javax.imageio.spi.IIOServiceProvider])
(require '[javax.imageio.spi.ImageInputStreamSpi])
(require '[javax.imageio.spi.ImageOutputStreamSpi])
(require '[javax.imageio.spi.ImageReaderSpi])
(require '[javax.imageio.spi.ImageReaderWriterSpi])
(require '[javax.imageio.spi.ImageTranscoderSpi])
(require '[javax.imageio.spi.ImageWriterSpi])
(require '[javax.imageio.spi.RegisterableService])
(require '[javax.imageio.spi.ServiceRegistry$Filter])
(require '[javax.imageio.spi.ServiceRegistry])
