(ns javax.xml.stream.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[javax.xml.stream.EventFilter])
(require '[javax.xml.stream.FactoryConfigurationError])
(require '[javax.xml.stream.Location])
(require '[javax.xml.stream.StreamFilter])
(require '[javax.xml.stream.XMLEventFactory])
(require '[javax.xml.stream.XMLEventReader])
(require '[javax.xml.stream.XMLEventWriter])
(require '[javax.xml.stream.XMLInputFactory])
(require '[javax.xml.stream.XMLOutputFactory])
(require '[javax.xml.stream.XMLReporter])
(require '[javax.xml.stream.XMLResolver])
(require '[javax.xml.stream.XMLStreamConstants])
(require '[javax.xml.stream.XMLStreamException])
(require '[javax.xml.stream.XMLStreamReader])
(require '[javax.xml.stream.XMLStreamWriter])
